Feature2 added with multiple files
smnighim/Django pull request #6
Opened 2024-03-17 11:01 UTC by Nimeshworkstation

i have added geeta and quran

2024-03-17 11:06 UTC, smnighim commented on feature2/show.html.txt
> +
change title

2024-03-17 11:06 UTC, smnighim commented on feature2/hide.html.txt
> +hello hanuman jee, kaise ho aap ?
hanumnam jee must be in capital

2024-03-17 11:08 UTC, smnighim requested changes
need necessary actions

2024-03-18 08:22 UTC, Nimeshworkstation commented on feature2/show.html.txt
> +
i have done change in title

2024-03-18 08:28 UTC, closed without merging